#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

if [[ -z "$PLUSHU_BUILDPACKS_DIR" ]]; then
  echo "No buildpacks dir defined; aborting." >&2
  exit 1
fi

config_url=https://raw.githubusercontent.com/progrium/buildstep/master/builder/config/buildpacks.txt

i=`ls -f "$PLUSHU_BUILDPACKS_DIR" | wc -l`

while read url; do
  buildpack=${url%https://github.com/*/}
  buildpack=${buildpack##.git#*}
  "$PLUSHU_ROOT/lib/plushook" install-buildpack $(printf '%02i_%s' \
    "$i" "${buildpack##*/}") "https://github.com/$buildpack.git"
  i=$((i+1))
done < <(curl "$config_url" 2>&1 || cat <<EOF
https://github.com/ddollar/heroku-buildpack-multi.git
https://github.com/heroku/heroku-buildpack-ruby.git
https://github.com/heroku/heroku-buildpack-nodejs.git
https://github.com/heroku/heroku-buildpack-clojure.git
https://github.com/heroku/heroku-buildpack-python.git
https://github.com/heroku/heroku-buildpack-java.git
https://github.com/heroku/heroku-buildpack-gradle.git
https://github.com/heroku/heroku-buildpack-grails.git
https://github.com/heroku/heroku-buildpack-scala.git
https://github.com/heroku/heroku-buildpack-play.git
https://github.com/heroku/heroku-buildpack-php.git
https://github.com/heroku/heroku-buildpack-go.git
EOF
)
